# SL-minetest-server 2.0 基础配置
server_name = SL-Minetest-Server 2.0 (EKS Cloud)
server_description = Welcome to the Cloud Native Minetest Server! Built with AWS EKS.
port = 30000
max_users = 15
default_game = minetest

# 禁用作弊，开启伤害
enable_damage = true
creative_mode = false

# 将世界数据保存在特定目录（等下 K8s 会把 EFS 挂载到这个目录）
map-dir = /var/lib/minetest/.minetest/worlds/world